function dataIndex = makeDataIndex(logfilepath, analysispath, FolderOnly)
% % makeDataIndex %
%PURPOSE:   Make a table of the behavioral log files
%AUTHORS:   H Atilgan and AC Kwan 191127
%
%INPUT ARGUMENTS
%   logfilepath:  where to look for the logfiles generated by NBS Presentation
%   analysispath: where to save the behavioral .mat files
%   FolderOnly : (optional), Specific folder name string to create table 
%               for. If not defined, it will include all behaviour log  
%               files. It needs a string for exact folder name.
%
%OUTPUT ARGUMENTS
%   dataIndex:    a table of the data files
%

%% Look for valid log files
if nargin <= 2
    % search all subfolders within the specified path
    AllLogfiles = dir(fullfile(logfilepath,'**','*.log'));
else
    % search all subfolders within the specified path
    AllLogfiles = dir(fullfile(logfilepath,FolderOnly,'**','*.log'));
    AllLogfiles = AllLogfiles(arrayfun(@(x) ~strcmp(x.name(1),'.'),AllLogfiles)); % necessary for hidden files if there is any
end

nFile = size(AllLogfiles,1);
disp(['Total number of behavioral logfiles detected = ', num2str(nFile)]);

%% Create data index table

dataIndex = table(...
    (1:nFile)',...
    cell(nFile,1),...
    cell(nFile,1),...
    cell(nFile,1)...
    );

dataIndex.Properties.VariableNames = {...
    'Index',...
    'LogFileName',...
    'LogFilePath',...
    'BehPath'...
    };

%%  Get info about each logfile
for b = 1:nFile
   
    % Info about the logfile
    dataIndex.LogFilePath(b) = {AllLogfiles(b).folder};
    dataIndex.LogFileName(b) = {AllLogfiles(b).name};
           
    % Info about analysis file
    subfolderName = AllLogfiles(b).folder(numel(logfilepath)+1:end); %identify name of the subfolder for which data reside
    behPath = fullfile(analysispath,subfolderName);      %recreate the folder structure in /data but now in /analysis
    dataIndex.BehPath(b) = {behPath};

    % Create directory to store analysis    
    if ~exist(behPath,'dir')
        mkdir(behPath);
    end

end