function plot_switch_hrside_M2stimulation(input,input2,tlabel)
% % plot_switch_hrside_M2stimulation %
%PURPOSE:   Plot choice behavior around switches, when the high reward
%           side has changed, pre vs post-lesion
%AUTHORS:   AC Kwan 170518
%
%INPUT ARGUMENTS
%   input:  Structure generated by choice_switch_hrside(), pre-lesion.
%   input2: Structure generated by choice_switch(), post-lesion
%   tlabel: Text string that will be put on top of the figure

%%
if numel(input) <= 1 || numel(input2) <= 1
    error('Error in plot_switch_hrside_lesion: Expecting >1 session of data as inputs');
end

dat(1).input = input;
dat(1).label = 'Pre-lesion';
dat(1).linestyle='v-';
dat(1).color  =[0 0 0];
dat(2).input = input2;
dat(2).label = 'Post-lesion';
dat(2).linestyle='-';
dat(2).color  =[0 150/256 0];

n=input{1}.n;

for kk=1:2
    for j=1:numel(dat(kk).input)
        temp_probh(:,j)=dat(kk).input{j}.probh;
        temp_probl(:,j)=dat(kk).input{j}.probl;
        temp_probn(:,j)=dat(kk).input{j}.probneither;
    end
    dat(kk).probh=nanmean(temp_probh,2);
    dat(kk).probl=nanmean(temp_probl,2);
    dat(kk).probn=nanmean(temp_probn,2);
    dat(kk).probh_sem=nanstd(temp_probh,[],2)./sqrt(numel(dat(kk).input));
    dat(kk).probl_sem=nanstd(temp_probl,[],2)./sqrt(numel(dat(kk).input));
    dat(kk).probn_sem=nanstd(temp_probn,[],2)./sqrt(numel(dat(kk).input));
    
    clearvars temp_probl temp_probr temp_probn;
end

figure;
subplot(1,2,1); hold on;

legendNum = 1;

for kk=1:2
    %plot the mean
    h(legendNum)=plot(n,dat(kk).probh,'-','MarkerSize',30,'Linewidth',3,'Color',dat(kk).color);
    legstring{legendNum}=['Initial better option, ' dat(kk).label];
    legendNum = legendNum + 1;
    
    h(legendNum)=plot(n,dat(kk).probl,'-.','MarkerSize',30,'Linewidth',3,'Color',dat(kk).color);
    legstring{legendNum}=['Initial worse option, ' dat(kk).label];
    legendNum = legendNum + 1;
    
    h(legendNum)=plot(n,dat(kk).probn,':','MarkerSize',30,'Linewidth',3,'Color',dat(kk).color);
    legstring{legendNum}=['Miss, ' dat(kk).label];
    legendNum = legendNum + 1;
    
    %plot dotted line at trial = 0
    plot([0 0],[0 1],'k--','LineWidth',2);
    
    %plot the error bars
    for l=1:numel(n)
        plot(n(l)*[1 1],dat(kk).probh(l)+dat(kk).probh_sem(l)*[-1 1],'-','LineWidth',3,'Color',dat(kk).color);
        plot(n(l)*[1 1],dat(kk).probl(l)+dat(kk).probl_sem(l)*[-1 1],'-','LineWidth',3,'Color',dat(kk).color);
        plot(n(l)*[1 1],dat(kk).probn(l)+dat(kk).probn_sem(l)*[-1 1],'-','LineWidth',3,'Color',dat(kk).color);
    end
    
end

legend(h,legstring);
legend box off;
ylabel('Fraction of trials');
xlabel('Trial from block switch');
axis([n(1) n(end) 0 1]);
title(tlabel);

end


