function plot_behperf_lesion_hitRates(input,input2,tlabel)
% % plot_behperf_lesion %
%PURPOSE:   Plot basic performance metrics, pre vs post-lesion
%AUTHORS:   AC Kwan 191210
%
%INPUT ARGUMENTS
%   input:  Structure generated by beh_performance(), pre-lesion
%   input2: Structure generated by beh_performance(), post-lesion
%   tlabel: Text string that will be put on top of the figure

%%
if numel(input) <= 1 || numel(input2) <= 1
    error('Error in plot_switch_lesion: Expecting >1 session of data as inputs');
end

input = cell2mat(input);
input = squeeze(cell2mat(struct2cell(input)));

input2 = cell2mat(input2);
input2 = squeeze(cell2mat(struct2cell(input2)));



nLenght = max( size(input,2),size(input2,2));
x = ones(nLenght,4).*[1:4];
y = nan(nLenght,4);
y(:,1) = input(1,:); % pre-left
y(1:size(input2,2),2) = input2(1,:); % post-left
y(:,3) = input(2,:); % pre-right
y(1:size(input2,2),4) = input2(2,:); % pre-right

mean_y = nanmean(y);
figure;

%violinplot(y,x,'ViolinColor',[0 0 0],'ViolinAlpha',0.8,'EdgeColor',[0.5 0.5 0.5],'BoxColor',[0.5 0.5 0.5],'MedianColor',[1 0 0],'ShowData',false);

% box plot - servicable, but something else may be better?
% h = boxplot(y,x,'Colors','k','Notch','on','Symbol',' ');
% set(h,{'linew'},{2})

% beeswarm plot - this implementation does not look good with many data points
% beeswarm(x(1:116,1:4),y(1:116,1:4));

% bar plot - not very informative
subplot(2,1,1)
barh(1,mean_y(:,1),0.5,'LineWidth',3,'FaceColor','k','EdgeColor','k'); hold on
barh(2,mean_y(:,2),0.5,'LineWidth',3,'FaceColor',[0 150/256 0],'EdgeColor',[0 150/256 0]);

barh(3.5,mean_y(:,3),0.5,'LineWidth',3,'FaceColor','k','EdgeColor','k'); hold on
barh(4.5,mean_y(:,4),0.5,'LineWidth',3,'FaceColor',[0 150/256 0],'EdgeColor',[0 150/256 0]);

 er = errorbar(mean_y,[1  2 3.5 4.5],nanstd(y)/sqrt(numel(y)),nanstd(y)/sqrt(numel(y)),'k.','horizontal','LineWidth',2);

xlim([70 82]);
box off
xlabel('Hit rates (%)');
ylim([0 5.5]);
set(gca,'ytick',[1 2 3.5 4.5]);
set(gca,'yticklabel',{'Pre','Post','Pre','Post'});

  
p=ranksum(y(:,1), y(:,2));
title(['p-val = ' num2str(p,2)]);
    
p=ranksum(y(:,3), y(:,4));
title(['p-val = ' num2str(p,2)])


end


