function plot_switch_random_lesion(input,input2,tlabel,rule_labels)
% % plot_switch_random_lesion %
%PURPOSE:   Plot choice behavior around switches, as a function of
%           statistics of the block preceding the switch, pre vs post-lesion
%AUTHORS:   AC Kwan 191209
%
%INPUT ARGUMENTS
%   input:  Structure generated by choice_switch_random(), pre-lesion
%   input2:  Structure generated by choice_switch_random(), post-lesion
%   tlabel: Text string that will be put on top of the figure
%   rule_labels:    Text strings for the legend in figure
%

%%
if numel(input) <= 1 || numel(input2) <= 1
    error('Error in plot_switch_lesion: Expecting >1 session of data as inputs');
end

dat(1).input = input;
dat(1).label = 'Pre-lesion';
dat(1).color =  flip(brewermap(5,'Greys'));
dat(2).input = input2;
dat(2).label = 'Post-lesion';
dat(2).color = flip(brewermap(5,'Greens'));

n=input{1}.n;
numtransType=input{1}.numtransType;
transType=input{1}.transType;
numRange=input{1}.numRange;
L1_ranges=input{1}.L1_ranges;
L2_ranges=input{1}.L2_ranges;
    
for kk=1:2
    for j=1:numel(dat(kk).input)
        temp_probl(:,:,:,j)=dat(kk).input{j}.probl;
        temp_probr(:,:,:,j)=dat(kk).input{j}.probr;
        temp_probn(:,:,:,j)=dat(kk).input{j}.probneither;
    end
    dat(kk).probl=nanmean(temp_probl,4);
    dat(kk).probr=nanmean(temp_probr,4);
    dat(kk).probn=nanmean(temp_probn,4);
    dat(kk).probl_sem=nanstd(temp_probl,[],4)./sqrt(numel(dat(kk).input));
    dat(kk).probr_sem=nanstd(temp_probr,[],4)./sqrt(numel(dat(kk).input));
    dat(kk).probn_sem=nanstd(temp_probn,[],4)./sqrt(numel(dat(kk).input));
    
    clearvars temp_probl temp_probr temp_probn;
end

figure;

for j=1:numtransType
    
    subplot(1,numtransType,j); hold on;
    
    legstring=[];
    legendNum = 1;

    %plot dotted line at trial = 0
    plot([0 0],[0 1],'k--','LineWidth',2);

    for kk=1:2
        %plot probability of going left
        for k=1:numRange
            %plot the mean
            h(legendNum) = plot(n,dat(kk).probl(:,j,k),'.-','MarkerSize',30,'Linewidth',3,'Color',dat(kk).color(k,:));
            %if more than 1 data set, then plot the error bars
%             if numel(input)>1
%                 for l=1:numel(n)
%                     plot(n(l)*[1 1],dat(kk).probl(l,j,k)+dat(kk).probl_sem(l,j,k)*[-1 1],'-','LineWidth',3,'Color',[1 k/(numRange+1) 0]);
%                 end
%             end
            
            legstring{legendNum}=['Left (L_C: ' int2str(L1_ranges(k,1)) '-' int2str(L1_ranges(k,2)) '; L_R: ' int2str(L2_ranges(k,1)) '-' int2str(L2_ranges(k,2)) '),' dat(kk).label];
            legendNum = legendNum + 1;
            
        end
        
        %plot probability of going right
        for k=1:numRange
            %plot the mean
            h(legendNum) = plot(n,dat(kk).probr(:,j,k),'v-','MarkerSize',7,'Linewidth',3,'Color',dat(kk).color(k,:));
            %if more than 1 data set, then plot the error bars
%             if numel(input)>1
%                 for l=1:numel(n)
%                     plot(n(l)*[1 1],dat(kk).probr(l,j,k)+dat(kk).probr_sem(l,j,k)*[-1 1],'-','LineWidth',3,'Color',[0 k/(numRange+1) 1]);
%                 end
%             end
            
            legstring{legendNum}=['Right (L_C: ' int2str(L1_ranges(k,1)) '-' int2str(L1_ranges(k,2)) '; L_R: ' int2str(L2_ranges(k,1)) '-' int2str(L2_ranges(k,2)) '),' dat(kk).label];
            legendNum = legendNum + 1;
            
       end
        
        %plot probability of miss
        for k=1:numRange
            %plot the mean
            h(legendNum) = plot(n,dat(kk).probn(:,j,k),':','MarkerSize',30,'Linewidth',3,'Color',dat(kk).color(k,:));
            %if more than 1 data set, then plot the error bars
%             if numel(input)>1
%                 for l=1:numel(n)
%                     plot(n(l)*[1 1],dat(kk).probn(l,j,k)+dat(kk).probn_sem(l,j,k)*[-1 1],'-','LineWidth',3,'Color',k/(numRange+1)*[1 1 1]);
%                 end
%             end
            
            legstring{legendNum}=['Miss (L_C: ' int2str(L1_ranges(k,1)) '-' int2str(L1_ranges(k,2)) '; L_R: ' int2str(L2_ranges(k,1)) '-' int2str(L2_ranges(k,2)) '),' dat(kk).label];
            legendNum = legendNum + 1;
            
        end
     end
%     
     legend(h,legstring);
     legend box off;
    ylabel('Fraction of trials');    
    xlabel('Trial from block switch');
    axis([n(1) n(end) 0 1]);
    title([rule_labels{transType(j,1)} ' to ' rule_labels{transType(j,2)}]);
    
    clear legstring h;

end

end


