function plot_logreg_lesion(input,input2,tlabel)
% % plot_logreg_lesion %
%PURPOSE:   Plot logistic regression analysis of choice behavior
%AUTHORS:   AC Kwan 191208
%
%INPUT ARGUMENTS
%   input:  Structure generated by logistic_reg(), pre-lesion.
%   input2:  Structure generated by logistic_reg(), post-lesion.
%   tlabel: Text string that will be put on top of the figure

pvalThresh = 0.01;      %criterion for stat. significance

%%
if numel(input) <= 1 || numel(input2) <= 1
    error('Error in plot_logreg_lesion: Expecting >1 session of data as inputs');
end

dat(1).input = input;
dat(1).label = 'Pre-lesion';
dat(1).linestyle='--';
dat(1).color  =[0 0 0];
dat(2).input = input2;
dat(2).label = 'Post-lesion';
dat(2).linestyle='.-';
dat(2).color  =[0 150/256 0];

n=input{1}.n;
b_label=input{1}.b_label;

for kk=1:2
    for j=1:numel(dat(kk).input)
        dat(kk).b_biasAll(j)=dat(kk).input{j}.b_bias;
        dat(kk).b_coeffAll(:,:,j)=dat(kk).input{j}.b_coeff;
    end
    
    % calculating median!
    % if using mean - plot could be skewed by a few sessions/animals with very
    % large coefficients due to ill-conditioned regression analysis
    dat(kk).b_bias=nanmedian(dat(kk).b_biasAll);
    dat(kk).b_coeff=nanmedian(dat(kk).b_coeffAll,3);
end

%statistical significance - non-parametric sign-rank test, pre vs post-lesion
pval_bias = ranksum(dat(1).b_biasAll,dat(2).b_biasAll);
for k=1:size(dat(1).b_coeffAll,1)
    for j=1:size(dat(1).b_coeffAll,2)
        pval_coeff(k,j) = ranksum(squeeze(dat(1).b_coeffAll(k,j,:)),squeeze(dat(1).b_coeffAll(k,j,:)));
    end
end

maxY=max([dat(1).b_bias max(dat(1).b_coeff(:)) dat(2).b_bias max(dat(2).b_coeff(:))]);
numcoeffType = size(dat(1).b_coeff,2); %number of types of coefficients

trialIntoPast = -1*n;

figure;
subplot(2,2,1); hold on;

legstring=[];
legendNum = 1;

linestyle = [ {'v-'};{'s--'}];
for kk=1:2
    
    for j=1:numcoeffType
        h(legendNum)=plot(trialIntoPast,dat(kk).b_coeff(:,j),linestyle{j},...
            'MarkerSize',10,'LineWidth',3,'MarkerFaceColor',dat(kk).color,'Color',dat(kk).color);
        legstring{legendNum}=[b_label{j} ', ' dat(kk).label];
        legendNum = legendNum + 1;
    end
    plot([-100 100],[0 0],'k--','LineWidth',2);
    plot(0,dat(kk).b_bias,'k.','MarkerSize',30);
        
end

%plot markers for stat. significant data points
for k=1:numel(trialIntoPast)
    for j=1:numcoeffType
        if pval_coeff(k,j)<pvalThresh
            plot(trialIntoPast(k),maxY+0.3*(numcoeffType-j+1),'v','MarkerSize',15,...
                'LineWidth',3,'MarkerEdgeColor',dat(kk).color);
        end
    end
end
if pval_bias<pvalThresh
    plot(0,maxY+0.3,'v','MarkerSize',15,'LineWidth',3,'MarkerFaceColor','w','MarkerEdgeColor','k');
end

legend(h,legstring,'Location','Northwest');
legend box off;
ylabel('Weight');
xlabel('Trial into past');
xlim([-0.5 trialIntoPast(end)+0.5]);
ylim([-0.7 maxY+0.3*numcoeffType+0.1]);
set(gca,'XDir','reverse')
title(tlabel);

end
