function plot_behperf_longitudinal(input,input2,tlabel)
% % plot_behperf_longitudinal %
%PURPOSE:   Plot basic performance metrics, a specified number of 
%first vs last Phase 3 sessions
%AUTHORS:   AC Kwan 191210
%
%INPUT ARGUMENTS
%   input:  Structure generated by beh_performance(), first sessions
%   input2: Structure generated by beh_performance(), last sessions
%   tlabel: Text string that will be put on top of the figure

%%
if numel(input) <= 1 || numel(input2) <= 1
    error('Error in plot_switch_lesion: Expecting >1 session of data as inputs');
end

dat(1).input = input;
dat(1).label = 'naive';
dat(2).input = input2;
dat(2).label = 'trained';

rule_labels=input{1}.rule_labels;

for kk=1:2
    for j=1:numel(dat(kk).input)   
        dat(kk).nTrial(j)=dat(kk).input{j}.nTrial;
        dat(kk).nLeftResp(j)=dat(kk).input{j}.nLeftResp;
        dat(kk).nRightResp(j)=dat(kk).input{j}.nRightResp;
        dat(kk).meanRewardRate(:,j)=dat(kk).input{j}.meanRewardRate;
        dat(kk).meanHitRate(:,j)=dat(kk).input{j}.meanHitRate;
        dat(kk).nSwitch(j)=dat(kk).input{j}.nSwitch;
        dat(kk).meanTrialtoCrit(:,j)=dat(kk).input{j}.meanTrialtoCrit;
     end
end

figure;
   
for j=1:10

    if j==1
        temp1 = dat(1).nTrial;
        temp2 = dat(2).nTrial;
        templabel = 'Trials';
        ymax = 1400;
   elseif j==2
        temp1 = dat(1).nSwitch;
        temp2 = dat(2).nSwitch;
        templabel = 'Block switches';
        ymax = 50;
    elseif j==3
        temp1 = dat(1).nLeftResp;
        temp2 = dat(2).nLeftResp;
        templabel = 'Left responses';
        ymax = 800;
    elseif j==4
        temp1 = dat(1).nRightResp;
        temp2 = dat(2).nRightResp;
        templabel = 'Right responses';
        ymax = 800;
    elseif j==5
        temp1 = dat(1).meanRewardRate(1,:);
        temp2 = dat(2).meanRewardRate(1,:);
        templabel = [{'Reward rate'}; {[rule_labels{1} ' blocks']}];
        ymax = 70;
    elseif j==6
        temp1 = dat(1).meanRewardRate(2,:);
        temp2 = dat(2).meanRewardRate(2,:);
        templabel = [{'Reward rate'}; {[rule_labels{2} ' blocks']}];
        ymax = 70;
    elseif j==7
        temp1 = dat(1).meanHitRate(1,:);
        temp2 = dat(2).meanHitRate(1,:);
        templabel = [{'Hit rate'}; {[rule_labels{1} ' blocks']}];
        ymax = 100;
    elseif j==8
        temp1 = dat(1).meanHitRate(2,:);
        temp2 = dat(2).meanHitRate(2,:);
        templabel = [{'Hit rate'}; {[rule_labels{2} ' blocks']}];
        ymax = 100;
    elseif j==9
        temp1 = dat(1).meanTrialtoCrit(1,:);
        temp2 = dat(2).meanTrialtoCrit(1,:);
        temp1 = temp1(~isinf(temp1));
        temp2 = temp2(~isinf(temp2));
        templabel = [{'Trials to criterion'}; {[rule_labels{1} ' blocks']}];
        ymax = 70;
    elseif j==10
        temp1 = dat(1).meanTrialtoCrit(2,:);
        temp2 = dat(2).meanTrialtoCrit(2,:);
        temp1 = temp1(~isinf(temp1));
        temp2 = temp2(~isinf(temp2));
        templabel = [{'Trials to criterion'}; {[rule_labels{2} ' blocks']}];
        ymax = 70;

    end
    
    subplot(3,4,j); hold on;
 
    % violin plot
    x = [1*ones(size(temp1')); 2*ones(size(temp2'))];
    y = [temp1'; temp2'];
    
    violinplot(y,x,'ViolinColor',[0 0 0],'ViolinAlpha',0.8,'EdgeColor',[0.5 0.5 0.5],'BoxColor',[0.5 0.5 0.5],'MedianColor',[1 0 0],'ShowData',false);
    
    % box plot - servicable, but something else may be better?
    % h = boxplot(y,x,'Colors','k','Notch','on','Symbol',' ');
    % set(h,{'linew'},{2})
    
    % beeswarm plot - this implementation does not look good with many data points
    % beeswarm(x,y,'rand','none',3);

    % bar plot - not very informative
    % bar(1,nanmean(temp1),0.5,'LineWidth',3,'FaceColor','w','EdgeColor','k');
    % bar(2,nanmean(temp2),0.5,'LineWidth',3,'FaceColor','w','EdgeColor','k');
    
    p=ranksum(temp1, temp2);
    title(['p-val = ' num2str(p,2)]);
    
    ylabel(templabel);
    ylim([0 ymax]);
    set(gca,'xtick',[1 2]);
    set(gca,'xticklabel',{'naive','trained'});
    xlim([0 3]);

    
end


