function plot_switch_longitudinal(input,input2,tlabel,rule_labels)
% % plot_switch_longitudinal %
%PURPOSE:   Plot choice behavior around switches, a specified number of 
%first vs last Phase 3 sessions
%AUTHORS:   AC Kwan 191208
%
%INPUT ARGUMENTS
%   input:  Structure generated by choice_switch(), first sessions
%   input2: Structure generated by choice_switch(), last sessions
%   tlabel: Text string that will be put on top of the figure
%   rule_labels:    Text strings for the legend in figure

%%
if numel(input) <= 1 || numel(input2) <= 1
    error('Error in plot_switch_lesion: Expecting >1 session of data as inputs');
end

dat(1).input = input;
dat(1).label = 'naive';
dat(1).color = 'k';
dat(2).input = input2;
dat(2).label = 'trained';
dat(2).color = [0 150/256 0];

n=input{1}.n;
numtransType=input{1}.numtransType;
transType=input{1}.transType;

for kk=1:2
    for j=1:numel(dat(kk).input)
        temp_probl(:,:,j)=dat(kk).input{j}.probl;
        temp_probr(:,:,j)=dat(kk).input{j}.probr;
        temp_probn(:,:,j)=dat(kk).input{j}.probneither;
    end
    dat(kk).probl=nanmean(temp_probl,3);
    dat(kk).probr=nanmean(temp_probr,3);
    dat(kk).probn=nanmean(temp_probn,3);
    dat(kk).probl_sem=nanstd(temp_probl,[],3)./sqrt(numel(dat(kk).input));
    dat(kk).probr_sem=nanstd(temp_probr,[],3)./sqrt(numel(dat(kk).input));
    dat(kk).probn_sem=nanstd(temp_probn,[],3)./sqrt(numel(dat(kk).input));
    
    clearvars temp_probl temp_probr temp_probn;
end

figure;

for j=1:numtransType
    
    subplot(1,numtransType,j); hold on;
    
    legstring=[];
    legendNum = 1;
    
    %plot dotted line at trial = 0
    plot([0 0],[0 1],'k--','LineWidth',2);
    
    for kk=1:2
        %plot the mean
        h(legendNum)=plot(n,dat(kk).probl(:,j),'-','MarkerSize',30,'Linewidth',3,'Color',dat(kk).color);
        legstring{legendNum}=['Left, ' dat(kk).label];
        legendNum = legendNum + 1;
        
        h(legendNum)=plot(n,dat(kk).probr(:,j),'-.','MarkerSize',30,'Linewidth',3,'Color',dat(kk).color);
        legstring{legendNum}=['Right, ' dat(kk).label];
        legendNum = legendNum + 1;
        
        h(legendNum)=plot(n,dat(kk).probn(:,j),':','MarkerSize',30,'Linewidth',3,'Color',dat(kk).color);
        legstring{legendNum}=['Miss, ' dat(kk).label];
        legendNum = legendNum + 1;
        
        %plot the error bars
        for l=1:numel(n)
            plot(n(l)*[1 1],dat(kk).probl(l,j)+dat(kk).probl_sem(l,j)*[-1 1],'-','LineWidth',3,'Color',dat(kk).color);
            plot(n(l)*[1 1],dat(kk).probr(l,j)+dat(kk).probr_sem(l,j)*[-1 1],'-.','LineWidth',3,'Color',dat(kk).color);
            plot(n(l)*[1 1],dat(kk).probn(l,j)+dat(kk).probn_sem(l,j)*[-1 1],':','LineWidth',3,'Color',dat(kk).color);
        end
        
    end
    
    ylabel('Fraction of trials');
    xlabel('Trial from block switch');
    axis([n(1) n(end) 0 1]);
    title([rule_labels{transType(j,1)} ' to ' rule_labels{transType(j,2)}]);
    
    if j==1
        legend(h,legstring);
        legend boxoff
        legend ('location','west')
    end
    
end

end


