function plot_switch_hrside_witheachanimals(input,tlabel)
% % plot_switch_hrside_witheachanimals %
%PURPOSE:   Plot choice behavior around switches, when the high reward
%           side has changed
%AUTHORS:   H Atilgan & AC Kwan 03142020
%
%INPUT ARGUMENTS
%   input:  Structure generated by choice_switch_hrside().
%   tlabel: Text string that will be put on top of the figure

%% plot choice behaviour - high2low only with individual animals - for all animal
n=input{1}.n;
for j=1:numel(input)
    temp_probh(:,j)=input{j}.probh; 
    temp_probl(:,j)=input{j}.probl;
    temp_probn(:,j)=input{j}.probneither;
end
probh=nanmean(temp_probh,2);
probl=nanmean(temp_probl,2);
probn=nanmean(temp_probn,2);
probh_sem=nanstd(temp_probh,[],2)./sqrt(numel(input));
probl_sem=nanstd(temp_probl,[],2)./sqrt(numel(input));
probn_sem=nanstd(temp_probn,[],2)./sqrt(numel(input));

figure;
cmap =  brewermap(4,'PuOr');
subplot(1,2,1); hold on;
plot([0 0],[0 1],'k--','LineWidth',2);
plot(n,temp_probh,'-','LineWidth',1,'Color',cmap(2,:));
plot(n,temp_probl,'-','LineWidth',1,'Color',cmap(3,:));
plot(n,temp_probn,'-','LineWidth',1,'Color','k');

h(1) = plot(n,probh,'.-','MarkerSize',30,'Linewidth',3,'Color',cmap(1,:));
h(2) = plot(n,probl,'v-','MarkerSize',7,'Linewidth',3,'Color',cmap(4,:));
h(3) = plot(n,probn,'.-','MarkerSize',30,'Linewidth',3,'Color','k');

if numel(input)>1
    for l=1:numel(n)
        plot(n(l)*[1 1],probh(l)+probh_sem(l)*[-1 1],'-','LineWidth',3,'Color',cmap(1,:));
         plot(n(l)*[1 1],probl(l)+probl_sem(l)*[-1 1],'-','LineWidth',3,'Color',cmap(4,:));
        plot(n(l)*[1 1],probn(l)+probn_sem(l)*[-1 1],'-','LineWidth',3,'Color','k');
    end
end
ylabel('Fraction of trials');
xlabel('Trial from block switch');
title (tlabel )
axis([n(1) n(end) 0 1]);


legend(h,'Initial better option','Initial worse option','Miss');
legend (h,'location','west')
legend box off;
