function plot_switch_hrside_random_M2stimulation(input,input2,input3, tlabel)
% % plot_switch_hrside_random_M2stimulation %
%PURPOSE:   Plot choice behavior around switches, when the high reward
%           side has changed, pre vs post-lesion
%AUTHORS:   AC Kwan 191209
%
%INPUT ARGUMENTS
%   input:  Structure generated by choice_switch_hrside(), pre-lesion
%   input2:  Structure generated by choice_switch_hrside(), post-lesion
%   tlabel: Text string that will be put on top of the figure

%%
% if numel(input) <= 1 || numel(input2) <= 1
%     error('Error in plot_switch_lesion: Expecting >1 session of data as inputs');
% end

dat(1).input = input;
dat(1).label = 'No stimulation';
dat(1).color =  flip(brewermap(5,'Greys'));
dat(1).linestyle='.-';
dat(1).markerSize =30;

dat(2).input = input2;
dat(2).label = 'Stimulation Ipsi';
dat(2).color = flip(brewermap(5,'Blues'));
dat(2).linestyle='v-';
dat(2).markerSize =7;

dat(3).input = input3;
dat(3).label = 'Stimulation Contra';
dat(3).color = flip(brewermap(5,'Blues'));
dat(3).linestyle='s-';
dat(3).markerSize =7;

zn=input{1}.n;
numRange=input{1}.numRange;
L1_ranges=input{1}.L1_ranges;
L2_ranges=input{1}.L2_ranges;

for kk=1:3
    for j=1:numel(dat(kk).input)
        temp_probh(:,:,j)=dat(kk).input{j}.probh;
        temp_probl(:,:,j)=dat(kk).input{j}.probl;
        temp_probn(:,:,j)=dat(kk).input{j}.probneither;
    end
    dat(kk).probh=nanmean(temp_probh,3);
    dat(kk).probl=nanmean(temp_probl,3);
    dat(kk).probn=nanmean(temp_probn,3);
    dat(kk).probh_sem=nanstd(temp_probh,[],3)./sqrt(numel(dat(kk).input));
    dat(kk).probl_sem=nanstd(temp_probl,[],3)./sqrt(numel(dat(kk).input));
    dat(kk).probn_sem=nanstd(temp_probn,[],3)./sqrt(numel(dat(kk).input));
    
    clearvars temp_probl temp_probr temp_probn;
end

figure;

for kk=1:3
    subplot(1,3,kk); hold on;
    
    legstring=[];
    legendNum = 1;
    
    %plot dotted line at trial = 0
    plot([0 0],[0 1],'k--','LineWidth',2);
    
    %plot probability of choosing initial best option
    for k=1:numRange
        %plot the mean
        h(legendNum) = plot(n,dat(kk).probh(:,k),dat(1).linestyle,'MarkerSize',dat(1).markerSize,'Linewidth',3,'Color',dat(kk).color(k,:));
        %if more than 1 data set, then plot the error bars
        %     if numel(input)>1
        %         for l=1:numel(n)
        %             plot(n(l)*[1 1],dat(kk).probh(l,k)+dat(kk).probh_sem(l,k)*[-1 1],'-','LineWidth',3,'Color',[0 1 k/(numRange+1)]);
        %         end
        %     end
        
        legstring{legendNum}=['Initial better option (L_C: ' int2str(L1_ranges(k,1)) '-' int2str(L1_ranges(k,2)) '; L_R: ' int2str(L2_ranges(k,1)) '-' int2str(L2_ranges(k,2)) '),' dat(kk).label];
        legendNum = legendNum + 1;
    end
    
    %plot probability of choosing initial worse option
    for k=1:numRange
        %plot the mean
        h(legendNum) = plot(n,dat(kk).probl(:,k),dat(2).linestyle,'MarkerSize',dat(2).markerSize,'Linewidth',3,'Color',dat(kk).color(k,:));
        %if more than 1 data set, then plot the error bars
        %     if numel(input)>1
        %         for l=1:numel(n)
        %             plot(n(l)*[1 1],dat(kk).probl(l,k)+dat(kk).probl_sem(l,k)*[-1 1],'-','LineWidth',3,'Color',[1 k/(numRange+1) 1]);
        %         end
        %     end
        
        legstring{legendNum}=['Initial worse option (L_C: ' int2str(L1_ranges(k,1)) '-' int2str(L1_ranges(k,2)) '; L_R: ' int2str(L2_ranges(k,1)) '-' int2str(L2_ranges(k,2)) '),' dat(kk).label];
        legendNum = legendNum + 1;
    end
    
    %plot probability of choosing neither
    for k=1:numRange
        %plot the mean
        h(legendNum) = plot(n,dat(kk).probn(:,k),':','Marker','none', 'Linewidth',3,'Color',dat(kk).color(k,:));
        %if more than 1 data set, then plot the error bars
        %     if numel(input)>1
        %         for l=1:numel(n)
        %             plot(n(l)*[1 1],dat(kk).probn(l,k)+dat(kk).probn_sem(l,k)*[-1 1],'-','LineWidth',3,'Color',k/(numRange+1)*[1 1 1]);
        %         end
        %     end
        
        legstring{legendNum}=['Miss (L_C: ' int2str(L1_ranges(k,1)) '-' int2str(L1_ranges(k,2)) '; L_R: ' int2str(L2_ranges(k,1)) '-' int2str(L2_ranges(k,2)) '),' dat(kk).label];
        legendNum = legendNum + 1;
    end
end

%legend(h,legstring);
%legend box off;
ylabel('Fraction of trials');
xlabel('Trial from block switch');
axis([n(1) n(end) 0 1]);
title(tlabel);

end


