function plot_val_byTrialType_M2stimulation(input, input2)
% % plot_val_byTrialType_M2stimulation %
%PURPOSE:   Plot lick rates for different trial types, pre vs post-lesion
%AUTHORS:   AC Kwan 191209
%
%INPUT ARGUMENTS
%   input:        Structure generated by get_lickrate_byTrialType(), pre-lesion
%   input2:        Structure generated by get_lickrate_byTrialType(), post-lesion

%%
if numel(input) <= 1 || numel(input2) <= 1
    error('Error in plot_val_byTrialType_lesion: Expecting >1 session of data as inputs');
end

dat(1).input = input;
dat(1).label = 'No stimulation';
dat(1).linestyle=':';
dat(1).color  =[0 0 0];
dat(2).input = input2;
dat(2).label = 'Stimulation';
dat(2).linestyle='-';
dat(2).color  =[0 0 1];

% load from the cell array
edges=input{1}.edges;
trialType=input{1}.trialType;

for kk=1:2
    dat(kk).val = [];
    for j=1:numel(trialType)
        for l=1:numel(dat(kk).input)
            dat(kk).val(j,:,l)=dat(kk).input{l}.val{j};
        end
    end
end

%% calculate mean, and sem

for kk=1:2
    for j=1:numel(trialType)
        dat(kk).val_mean(:,j)=nanmean(dat(kk).val(j,:,:),3);
    end
    
    dat(kk).maxY=nanmax(dat(kk).val_mean(:));
end

%% plot

figure;

panel_h=ceil(numel(trialType)/2);

edges=edges+nanmean(diff(edges))/2; %plot at the center of the bins

for j=1:numel(trialType)
    
    subplot(2,panel_h,j); hold on;
    
    for kk=1:2
        plot(edges(1:end-1),dat(kk).val_mean(:,j),dat(kk).linestyle,'Linewidth',3,'Color',dat(kk).color);
    end
    plot([0 0],[0 max([dat(1).maxY dat(2).maxY])],'k--','LineWidth',2);
    legend({dat(1).label,dat(2).label});
    legend box off;
    xlim([edges(1) edges(end)]);
    ylim([0 max([dat(1).maxY dat(2).maxY])]);
    title(trialType{j},'interpreter','none');
    ylabel('Number of trials');
    xlabel(input{1}.valLabel);
    
end

end


