function plot_lickrate_byTrialType_M2stimulation(input, input2)
% % plot_lickrate_byTrialType_M2stimulation %
%PURPOSE:   Plot lick rates for different trial types, pre vs post-lesion
%AUTHORS:   AC Kwan 191209
%
%INPUT ARGUMENTS
%   input:    Structure generated by get_lickrate_byTrialType(), pre-lesion
%   input2:   Structure generated by get_lickrate_byTrialType(), post-lesion

maxY = 10;   %set limit of y-axis for plotting purpose

%%
if numel(input) <= 1 || numel(input2) <= 1
    error('Error in plot_lickrate_byTrialType_lesion: Expecting >1 session of data as inputs');
end

dat(1).input = input;
dat(1).label = 'No stimulation';
dat(1).linestyle=':';
dat(1).color  =[0 0 0];
dat(2).input = input2;
dat(2).label = 'Stimulation';
dat(2).linestyle='-';
dat(2).color  =[0 0 1];

% load from the cell array
edges=input{1}.edges;
trialType=input{1}.trialType;
trialLabel=input{1}.trialLabel;

for kk=1:2
    for j=1:numel(dat(kk).input)
        for l=1:numel(trialType)
            if j==1     %first time, load the array
                temp_lTimes{l}=dat(kk).input{j}.leftTimes{l};
                temp_rTimes{l}=dat(kk).input{j}.rightTimes{l};
            else        %otherwise, append
                temp_lTimes{l}=[(dat(kk).leftTimes{l}) dat(kk).input{j}.leftTimes{l}];
                temp_rTimes{l}=[(dat(kk).rightTimes{l}) dat(kk).input{j}.rightTimes{l}];
            end
        end
        dat(kk).leftTimes=temp_lTimes; 
        dat(kk).rightTimes=temp_rTimes;
        
        clearvars temp_lTimes temp_rTimes;
    end
end

%% calculate mean and sem
edges=edges(1:end-1)+nanmean(diff(edges))/2;   %plot using the center of the histogram bins

for kk=1:2
dat(kk).lTimes=nan(numel(edges),numel(trialType)); % of choosing left
dat(kk).rTimes=nan(numel(edges),numel(trialType)); % of choosing right
for j=1:numel(trialType)
    dat(kk).lTimes(:,j)=nanmean(dat(kk).leftTimes{j},2);
    dat(kk).rTimes(:,j)=nanmean(dat(kk).rightTimes{j},2);
    
    dat(kk).lTimes_sem(:,j)=nanstd(dat(kk).leftTimes{j},[],2)./sqrt(numel(dat(kk).input));
    dat(kk).rTimes_sem(:,j)=nanstd(dat(kk).rightTimes{j},[],2)./sqrt(numel(dat(kk).input));
end
end

%% plot
figure;

panel_h=numel(trialType);

for j=1:numel(trialType)
    
    subplot(2,panel_h,j); hold on;
    for kk=1:2
        plot(edges,dat(kk).lTimes(:,j),dat(kk).linestyle,'Linewidth',3,'Color',dat(kk).color);
    end
    plot([0 0],[0 maxY],'k--','LineWidth',2);
    legend({dat(1).label,dat(2).label});
    legend box off;
    title({trialLabel{j};'Left lick'},'interpreter','none');
    axis([edges(1) edges(end) 0 maxY]);
    xlabel('Time from cue (s)');
    ylabel('Lick density (Hz)');
    
    subplot(2,panel_h,j+numel(trialType)); hold on;
    for kk=1:2
        plot(edges,dat(kk).rTimes(:,j),dat(kk).linestyle,'Linewidth',3,'Color',dat(kk).color);
    end
    plot([0 0],[0 maxY],'k--','LineWidth',2);
    legend({dat(1).label,dat(2).label});
    legend box off;
    title({trialLabel{j};'Right lick'},'interpreter','none');
    axis([edges(1) edges(end) 0 maxY]);
    xlabel('Time from cue (s)');
    ylabel('Lick density (Hz)');
        
end

end


