function cellOrder = plot_snake(input,sortTime,xtitle,zscore)
% % plot_snake %
%PURPOSE:   Plot selectivity, based on PSTHs from one condition (i.e. a
%           snake plot)
%AUTHORS:   AC Kwan 170720
%
%INPUT ARGUMENTS
%   input:        Structure generated by get_psth()
%   sortTime:     Sort the cells based on signal value in this time period
%   xtitle:       Text to put as the label for x-axis.
%   zscore:       If true, then the input.signal contains z-score values,
%                 not dF/F (no need to further normalize here)
%
%OUTPUT ARGUMENTS
%   cellOrder:    Sorting order of the cells
%                 (could be fed back as input 'sortParam' for next call of
%                 this function)

if nargin < 4
    zscore = false;
end

%% Plotting parameters
%colors=cbrewer('div','RdBu',256);
%colors=flipud(colors);

colors=cbrewer('seq','OrRd',256);

%% Setup
t = input.t;
nTrials=size(input.signal,1);

signal=[];
for j=1:nTrials
    if (zscore)  %if z-score, then use z-score
        signal(:,j)=input.signal(j,:);
    else         %otherwise, normalize to range of 0 to 1
        signal(:,j)=(input.signal(j,:)-nanmin(input.signal(j,:)))./(nanmax(input.signal(j,:))-nanmin(input.signal(j,:)));
    end
end

% set up the y-axis range
if (zscore)
    ampl = max([abs(prctile(signal(:),95)) abs(prctile(signal(:),5))]);  %maximum deviation from zero
    maxY = ampl;   %make the scale symmetric around zero
    minY = -ampl;
else   %else dF/F had been normalized to a range from 0 to 1
    maxY=prctile(signal(:),95);
    minY=prctile(signal(:),5);
end

%% Make the pseudo-color snake plot

% PSTH is only reliable if there are at least several events.. 
% set threshold at 10
    image(t,1:nTrials,signal','CDataMapping','scaled');
    hold on; 
    plot([0 0],[0 nTrials+1],'w');
    colormap(colors);
    caxis([minY maxY]);      %normalize dF/F heatmap to max of all conditions
    ylabel('Trials');
    xlabel(xtitle);
    title(input.psth_label);
    
%     %make a color scale bar
%     subplot(3,20,50);
%     image(0,linspace(minY,maxY,100),linspace(minY,maxY,100)','CDataMapping','scaled');
%     colormap(colors);
%     if (zscore)
%         caxis([minY maxY]);
%         title('z-score');
%     else
%         caxis([0 1]);
%         title('Normalized dF/F');
%     end
%     set(gca,'YDir','normal');
%     set(gca,'XTick',[]);
end
